export const categories = [
  "Interpretação de Texto",
  "Gêneros Textuais",
  "Produção Textual",
  "Figuras de Linguagem",
  "Coesão e Coerência Textual",
  "Argumentação e Gêneros Argumentativos",
  "Norma Culta e Variação Linguística",
  "Funções da Linguagem",
  "Análise Sintática",
  "Literatura Brasileira",
  "Estilos e Movimentos Literários",
  "Pragmática",
  "Oralidade e Escrita",
  "Semântica",
  "Linguagem Corporal",
  "Esportes",
  "Lutas",
  "Saúde e Condicionamento Físico",
  "Lazer",
  "Artes Visuais",
  "Música",
  "Teatro",
  "Dança",
  "Expressão Artística e Cultural",
  "Patrimônio Cultural e Identidade",
  "Gêneros Literários",
  "Produção Literária e Sociedade",
  "Patrimônio Literário",
  "Literatura e Outras Artes",
  "Construção do Texto Literário",
  "Elementos do Texto Literário",
  "Gêneros Digitais",
  "Impacto das Tecnologias na Comunicação",
  "Compreensão Textual",
  "Cultura Anglo-Saxônica",
  "Tradução",
  "Gramática",
  "Cultura Hispânica",
  "Expressões Idiomáticas",
  "Brasil Pré-Colonial",
  "Brasil Colonial",
  "Independência do Brasil",
  "Império Brasileiro",
  "República Velha",
  "Era Vargas",
  "Ditadura Militar",
  "Brasil Contemporâneo",
  "Pré-História",
  "Antiguidade",
  "Idade Média",
  "Idade Moderna",
  "Idade Contemporânea",
  "Revoluções e Movimentos Sociais",
  "Guerras Mundiais",
  "Clima",
  "Vegetação",
  "Relevo",
  "Hidrografia",
  "Ecossistemas",
  "Geologia",
  "Recursos Naturais",
  "População",
  "Urbanização",
  "Globalização",
  "Desenvolvimento Sustentável",
  "Movimentos Migratórios",
  "Conflitos Territoriais",
  "Cidadania",
  "Direitos Humanos",
  "Movimentos Sociais",
  "Estratificação Social",
  "Cultura",
  "Identidade",
  "Relações de Gênero",
  "Ética",
  "Moral",
  "Filosofia Política",
  "Justiça",
  "Pensamento Crítico",
  "Células e Tecidos",
  "Metabolismo",
  "Genética",
  "Hereditariedade",
  "Organização dos Seres Vivos",
  "Ecologia",
  "Evolução",
  "Biotecnologia",
  "Saúde e Doenças",
  "Reino Animal e Vegetal",
  "Fisiologia Humana",
  "Genética Molecular",
  "Interações Ecológicas",
  "Preservação e Sustentabilidade",
  "Divisão Celular",
  "Ordem de Grandeza",
  "Notação Científica",
  "Sistema Internacional de Unidades",
  "Movimento e Equilíbrio",
  "Leis de Newton",
  "Leis de Kepler",
  "Hidrostática",
  "Energia, Trabalho e Potência",
  "Conservação de Energia",
  "Gravitação Universal",
  "Fenômenos Elétricos",
  "Fenômenos Magnéticos",
  "Ondas e Óptica",
  "Calor e Fenômenos Térmicos",
  "Termodinâmica",
  "Mecânica Quântica",
  "Física Moderna",
  "Acústica",
  "Oscilações",
  "Circuitos Elétricos",
  "Eletromagnetismo",
  "Física Nuclear",
  "Astrofísica",
  "Transformações",
  "Gases",
  "Reações Químicas",
  "Materiais",
  "Água e Soluções",
  "Energia e Reações",
  "Dinâmica Química",
  "Equilíbrio",
  "Química Orgânica",
  "Química e Tecnologia",
  "Fontes de Energia",
  "Propriedades Periódicas",
  "Cinética Química",
  "Termoquímica",
  "Soluções e Colóides",
  "Reações de Oxidação e Redução",
  "Química Inorgânica",
  "Polímeros",
  "Análise Química",
  "Química Ambiental",
  "Equações e inequações",
  "Funções",
  "Conjuntos",
  "Análise combinatória",
  "Probabilidade",
  "Geometria plana",
  "Geometria espacial",
  "Trigonometria",
  "Razões e proporções",
  "Porcentagem e juros",
  "Estatística",
  "Lógica proposicional",
  "Problemas lógicos",
  "Números Reais e Conjuntos Numéricos",
  "Polinômios",
  "Geometria Analítica",
  "Sistema de Equações",
];
